# Generated by Django 4.0.5 on 2022-06-08 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('team_alias', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('schedule_url', models.CharField(max_length=300, null=True)),
                ('team_url', models.CharField(max_length=300, null=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('url_schedule', models.CharField(blank=True, max_length=40, null=True)),
                ('url_team', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_permission', models.CharField(max_length=25, null=True)),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.league')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=50)),
                ('match_report_name', models.CharField(max_length=200)),
                ('jersey_number', models.CharField(max_length=3)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.league')),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', through='base.User_League', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='league',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.region'),
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=4)),
                ('season', models.CharField(max_length=12)),
                ('game_date', models.DateTimeField()),
                ('url', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=30)),
                ('oponent', models.CharField(max_length=200)),
                ('hosting', models.CharField(max_length=8)),
                ('team_enddate', models.DateTimeField()),
                ('punctuation_enddate', models.DateTimeField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('next_update', models.DateTimeField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.league')),
            ],
        ),
    ]
