# Generated by Django 4.0.4 on 2022-05-31 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_region_user_league_alter_league_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='region',
            new_name='name',
        ),
    ]
