# Generated by Django 4.0.5 on 2022-06-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_player_alias_alter_player_jersey_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='full_name',
        ),
    ]
