# Generated by Django 4.0.4 on 2022-05-31 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_region_region_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='region',
        ),
    ]
