# Generated by Django 4.0.4 on 2022-05-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_league_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='region',
            field=models.CharField(default=0, max_length=40, null=True),
        ),
    ]
