# Generated by Django 4.0.5 on 2022-06-10 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_player_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region_Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, null=True)),
                ('group_name', models.CharField(max_length=100, null=True)),
                ('group_url', models.CharField(max_length=300)),
                ('standing_url', models.CharField(max_length=300)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.region')),
            ],
        ),
    ]
