# Generated by Django 4.0.5 on 2022-06-10 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_region_groups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Region_Groups',
            new_name='Region_Group',
        ),
        migrations.CreateModel(
            name='Region_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('alias', models.CharField(max_length=20, null=True)),
                ('schedule_url', models.CharField(max_length=300, null=True)),
                ('team_url', models.CharField(max_length=300, null=True)),
                ('region_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.region_group')),
            ],
        ),
    ]
