# Generated by Django 4.0.4 on 2022-05-31 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_league_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_League',
        ),
    ]
