# Generated by Django 4.0.4 on 2022-05-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_user_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='region',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
