# Generated by Django 4.0.5 on 2022-06-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_region_groups_region_group_region_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='schedule_url',
        ),
        migrations.RemoveField(
            model_name='league',
            name='team_alias',
        ),
        migrations.RemoveField(
            model_name='league',
            name='team_url',
        ),
    ]
