# Generated by Django 4.0.5 on 2022-06-10 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_league_schedule_url_remove_league_team_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='region_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.region_team'),
        ),
    ]
