# Generated by Django 4.0.5 on 2022-06-29 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_league_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region_team',
            name='region_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.region_group'),
        ),
    ]
