# Generated by Django 4.0.5 on 2022-06-03 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_league_admins_league_host_league_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='league',
            name='team_alias',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=50)),
                ('macth_report_name', models.CharField(max_length=200)),
                ('jersey_number', models.CharField(max_length=3)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.league')),
            ],
        ),
        migrations.CreateModel(
            name='Match_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=4)),
                ('season', models.CharField(max_length=12)),
                ('game_date', models.DateTimeField()),
                ('url', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=30)),
                ('oponent', models.CharField(max_length=200)),
                ('home_game', models.CharField(max_length=8)),
                ('team_enddate', models.DateTimeField()),
                ('punctuation_enddate', models.DateTimeField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('next_update', models.DateTimeField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.league')),
            ],
        ),
    ]
