# Generated by Django 4.0.5 on 2022-06-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_username_user_league_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='token_to_join',
            field=models.CharField(default='AAAAAA', max_length=6),
        ),
    ]
