# Generated by Django 4.0.5 on 2022-06-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_league_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_league',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user_league',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='user_league',
            name='user_permission',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
