# Generated by Django 4.0.5 on 2022-07-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_player_alias_alter_player_jersey_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Player_Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default={})),
            ],
        ),
    ]
