# Generated by Django 4.0.5 on 2022-07-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_log_player_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_player_edit',
            name='data',
            field=models.JSONField(),
        ),
    ]
