# Generated by Django 4.0.5 on 2022-06-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_league_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='schedule_url',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='team_url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
