# Generated by Django 4.0.5 on 2022-07-09 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0016_log_player_edit_date_log_player_edit_editor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.CharField(blank=True, max_length=2, null=True)),
                ('is_starter', models.CharField(max_length=10)),
                ('goals', models.IntegerField()),
                ('pk_goals', models.IntegerField()),
                ('auto_goals', models.IntegerField()),
                ('yellow_cards', models.IntegerField()),
                ('red_cards', models.IntegerField()),
                ('votation_points', models.IntegerField()),
                ('report_points', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.calendar')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.player')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
