# Generated by Django 4.0.5 on 2022-06-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_league_schedule_url_league_team_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match_Report',
            new_name='Calendar',
        ),
    ]
