# Generated by Django 4.0.5 on 2022-07-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_match_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='user_teams_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
