# Generated by Django 4.0.5 on 2022-07-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_calendar_user_teams_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_report',
            name='mins_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match_report',
            name='report_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match_report',
            name='votation_points',
            field=models.IntegerField(null=True),
        ),
    ]
