# Generated by Django 4.0.5 on 2022-07-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_match_report_mins_played_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region_team',
            name='alias',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
